# Generated by Django 5.0.3 on 2024-04-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('user_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('is_favourite', models.BooleanField()),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_question', to='users.module')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_notes', to='users.module')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='users.question')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_users', to='users.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='users.user')),
            ],
        ),
    ]
