# Generated by Django 5.0.3 on 2024-04-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_review_delete_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='subject',
            new_name='title',
        ),
    ]
