# Generated by Django 5.0.3 on 2024-04-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModulesAndUsers',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
