# Generated by Django 5.0.3 on 2024-04-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_modulesandusers_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='MODULES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QUESTIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('favourite', models.BooleanField()),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modules')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='ANSWERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerID', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='USERMODULES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modules')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='RATING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingID', models.IntegerField()),
                ('ratingType', models.CharField(max_length=50)),
                ('answerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answers')),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modules')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='NOTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteID', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
