# Generated by Django 5.0.3 on 2024-04-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('user_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='answerID',
        ),
        migrations.RemoveField(
            model_name='usermodules',
            name='moduleID',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='moduleID',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='moduleID',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='questionID',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='usermodules',
            name='userID',
        ),
        migrations.CreateModel(
            name='User_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_users', to='main.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='main.user')),
            ],
        ),
        migrations.DeleteModel(
            name='ANSWERS',
        ),
        migrations.DeleteModel(
            name='MODULES',
        ),
        migrations.DeleteModel(
            name='NOTES',
        ),
        migrations.DeleteModel(
            name='QUESTIONS',
        ),
        migrations.DeleteModel(
            name='RATING',
        ),
        migrations.DeleteModel(
            name='USERMODULES',
        ),
        migrations.DeleteModel(
            name='USERS',
        ),
    ]
