# Generated by Django 5.0.3 on 2024-04-17 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notes_moduleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
