# Generated by Django 5.0.3 on 2024-04-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_answer_title_remove_question_add_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
