# Generated by Django 5.0.3 on 2024-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prifole_picture',
            field=models.ImageField(blank=True, default='uploads/default.png', upload_to='uploads/'),
        ),
    ]
