# Generated by Django 5.0.3 on 2024-04-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_profile_prifole_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prifole_picture',
            new_name='profile_picture',
        ),
    ]
