# Generated by Django 5.0.3 on 2024-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_profile_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='module1',
            field=models.CharField(default='COMP', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='module2',
            field=models.CharField(default='COMP', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='module3',
            field=models.CharField(default='COMP', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='module4',
            field=models.CharField(default='COMP', max_length=10),
        ),
    ]
