# Generated by Django 5.0.3 on 2024-04-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0015_profile_module1_profile_module2_profile_module3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
